version: "3.9"                            # The compose file version
services:                                 # Services section
  app-service:                            # Single service section
  # Image creation
    image: "rest-api_image"               # Name of the image to create
    build:                                # How to build the image
      context: rest-api-service           # Folder in which Dockerfile is contained
      dockerfile: Dockerfile              # Can leave empty if filename is Dockerfile 
    # Container Creation - Running  
    container_name: "rest-api_container"  # Name of the container to create
    env_file:
      - ./rest-api-service/docker.env     # Configuration file
    restart: "unless-stopped"             # Can be always, on-failure, unless-stopped
    networks:                             # Can define networks               
      - my-network                        
    ports:                                # Port mapping
      - 5000:80
    volumes:                              # Volume mapping
      - ./rest-api-service/shared-volume:/shared-volume
    depends_on:
      - mongo-service                       # Depends on db to start
  
  # My SQL Database Service
  mongo-service:
    image: mongo:latest
    container_name: mongo
    # restart: "on-failure"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=my_password
      - MONGO_INITDB_DATABASE=my_db
    networks:         
      - my-network
    ports:
      - '27017:27017'
    volumes:
      -  mongo-db:/data/db
      - ./mongo-service/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

volumes:
  mongo-db:
    driver: local

networks:
  my-network:
    name: my-network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "171.18.0.0/16"
          gateway: "171.18.0.1"