version: "3.9"                            # The compose file version
services:                                 # Services section
  app-service:                            # Single service section
  # Image creation
    image: "rest-api_image"               # Name of the image to create
    build:                                # How to build the image
      context: rest-api-service           # Folder in which Dockerfile is contained
      dockerfile: Dockerfile              # Can leave empty if filename is Dockerfile 
    # Container Creation - Running  
    container_name: "rest-api_container"  # Name of the container to create
    env_file:
      - ./rest-api-service/docker.env     # Configuration file
    restart: "unless-stopped"             # Can be always, on-failure, unless-stopped
    networks:                             # Can define networks               
      - my-network                        
    ports:                                # Port mapping
      - 5000:80
    volumes:                              # Volume mapping
      - ./rest-api-service/shared-volume:/shared-volume
    depends_on:
      - sql-service                       # Depends on db to start
  
  # My SQL Database Service
  sql-service:
    image: mysql:latest
    # container_name: "mysql-service"  # Name of the container to create
    cap_add:
      - SYS_NICE
    # restart: "on-failure"
    environment:
      - MYSQL_DATABASE=my_db
      - MYSQL_ROOT_PASSWORD=my_password
    networks:         
      - my-network
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
      - ./my-sql-service/db/init.sql:/docker-entrypoint-initdb.d/init.sql


volumes:
  db:
    driver: local

networks:
  my-network:
    name: my-network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "171.18.0.0/16"
          gateway: "171.18.0.1"